title: National Library Board
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#322987"
  secondary-color: "#dce5d3"
  media-colors:
    - title: media-color-one
      color: "#a60517"
    - title: media-color-two
      color: "#a60517"
    - title: media-color-three
      color: "#a60517"
    - title: media-color-four
      color: "#a60517"
    - title: media-color-five
      color: "#a60517"
resources_name: example-resource
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://nlb-learning-staging.netlify.app
prod: https://nlb-learning-prod.netlify.app
