title: LEARNX
url: https://learning.nlb.gov.sg
favicon: /images/learnXfavicon.png
google_analytics: UA-50449401-41
colors:
  primary-color: "#322987"
  secondary-color: "#322987"
  media-colors:
    - title: media-color-one
      color: "#a60517"
    - title: media-color-two
      color: "#a60517"
    - title: media-color-three
      color: "#a60517"
    - title: media-color-four
      color: "#a60517"
    - title: media-color-five
      color: "#a60517"
resources_name: example-resource
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3nz4gwa5i4qeb.amplifyapp.com/
prod: https://master.d3nz4gwa5i4qeb.amplifyapp.com/
is_government: true
shareicon: /images/isomer-logo.svg
facebook-pixel: ""
google_analytics_ga4: G-XLWNEK2W36
linkedin-insights: ""
